engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "app/**/*.css"
  - "app/**/*.js"
  - "app/**/*.jsx"
  - "__tests__/**/*.js"
exclude_paths: 
  - app/plugins/**/vendors/**/*
  - out/**/*
  - build/**/*